var films = [
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "Shazam",
        poster: "https://media.aintitcool.com/media/_versions/2019/dannie/newshazamposter_large.jpg",
        overview: "The guy has an amazing ability: if necessary, he can turn into an adult superhero with a single magic word.",
        release_date: 1553281200000,
        genres: ["Action", "Comedy", "Fantasy"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 486925200000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "Mr. Robot",
        poster: "https://m.media-amazon.com/images/M/MV5BMzgxMmQxZjQtNDdmMC00MjRlLTk1MDEtZDcwNTdmOTg0YzA2XkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg",
        overview: "Mr. Robot follows Elliot, a young programmer who works as a cyber-security engineer by day and as a vigilante hacker by night. Elliot finds himself at a crossroads when the mysterious leader of an underground hacker group recruits him to destroy the firm he is paid to protect.",
        release_date: 1435086000000,
        genres: ["Drama", "Psycho thriller", "Techno thriller"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "Avengers",
        poster: "https://upload.wikimedia.org/wikipedia/ru/3/3c/The_Avengers_2012_logo.jpg",
        overview: "Loki, Thor's half-brother, is back, and this time he's not alone. The earth is on the verge of enslavement, and only the best of the best can save humanity.",
        release_date: 1336071600000,
        genres: ["Action", "Fantasy", "Adventure"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "I Am Legend",
        poster: "https://m.media-amazon.com/images/M/MV5BYTE1ZTBlYzgtNmMyNS00ZTQ2LWE4NjEtZjUxNDJkNTg2MzlhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        overview: "An adaptation of Richard Matheson's novel of the same name about an unknown virus that killed half the world's population and turned the other half into vampires. The plot revolves around the only surviving person with inexplicable immunity, holding an endless siege of ghouls at night, and during the day trying to find an antidote and find out the causes of the epidemic.",
        release_date: 1513191600000,
        genres: ["Рorror", "Thriller", "Science fiction"],
    },
]