var films = [
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "Shazam",
        poster: "https://media.aintitcool.com/media/_versions/2019/dannie/newshazamposter_large.jpg",
        overview: "The guy has an amazing ability: if necessary, he can turn into an adult superhero with a single magic word.",
        release_date: 1553281200000,
        genres: ["Action", "Comedy", "Fantasy"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
    {
        id: String((Math.random(4)*100000).toFixed(0)),
        title: "The Goonies",
        poster: "https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/b7071274-0a3c-48d9-ba9e-3bb7354d8df9/600x900",
        overview: "In the film, kids who live in the \"Goon Docks\" neighborhood of Astoria, Oregon, attempt to save their homes from foreclosure and, in doing so, they discover an old treasure map that takes them on an adventure to unearth the long-lost fortune of One-Eyed Willy, a legendary 17th-century pirate.",
        release_date: 26848800000,
        genres: ["Adventure", "Comedy", "Romantic"],
    },
]